### ISSUE TITLE
Caching on CI seems to be broken

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#375] opened 2023-07-05 15:35 UTC
Last few times, the cache was 45 bytes...  Something's definitely quite broken. I'd appreciate some help, as my knowledge in this area is thin (and that's a generous description.)

**Comment by JacquesCarette** [comment] 2023-07-15 14:55
Still is broken. It's causing extra slowness in being able to accept PRs.

**Comment by JacquesCarette** [comment] 2023-07-15 17:52
Might be related to [this issue](https://github.com/actions/upload-artifact/issues/270). And also getting various warnings. Latest cache was also bogus.

**Comment by JasonGross** [comment] 2023-08-07 20:56
Maybe related to https://github.com/actions/cache/issues/624?  Also, maybe the cache action should be updated to v3?

**Comment by JasonGross** [comment] 2023-08-07 21:02
Plausibly the issue is that cabal seems to now be installing to `~/.local/state/cabal` instead of `~/.cabal`?

**Comment by JacquesCarette** [comment] 2023-08-07 21:07
Thanks - I'll investigate all those.

**Comment by JacquesCarette** [comment] 2023-08-07 21:42
Didn't mean to close this quite yet, I guess I used the 'wrong' words in my commit!

**Comment by JasonGross** [comment] 2023-08-07 21:45
Looks like you might also need to pass `--bindir` explicitly now, or else cache `~/.local/bin/`, because it seems that cabal is stuffing a symlink to the executables in `~/.local/bin`, and there aren't anywhere else in the cabal tree except /home/runner/.local/state/cabal/store/ghc-8.6.5/Agda-2.6.3-c7bd11606a8a3dcf5f3eb623c3877b0e1a7a34d151782f77a271cd5a0e48afca/bin/agda?

**Comment by JacquesCarette** [comment] 2023-08-08 18:53
Looks like this is now fixed. I'll wait for an independent PR to verify this before closing.

**Comment by Taneb** [comment] 2023-08-08 20:25
I merged master into #382. Looks like CI is still not working on PRs

**Comment by JacquesCarette** [comment] 2023-08-08 20:39
We've got partial success: the cache is there and has lots of stuff in it, and it is picked up. Part-way there.

Now to make sure the right things are in the path! Looks like various pieces disagree as to where to expect things to be.

**Comment by JacquesCarette** [comment] 2023-08-08 20:55
Still not working, sadly. I'm going to have to spend real time on it and test locally first.

**Comment by JasonGross** [comment] 2023-08-09 06:03
Replace `echo "~/.local/bin"` with `echo "$HOME/.local/bin"` when saving the path.  Pass `--installdir` explicitly to `cabal install` and make sure it's a directory that's cached.  Otherwise you can look at what I had to change to get https://github.com/JasonGross/lawvere/blob/main/.github/workflows/ci.yml working (which I pseudorandomly based off the CI in this repo)

**Closed** 2023-10-11 18:06 UTC
