### ISSUE TITLE
Library Unusable to stdlib 1.1 Users ---`levelOfTerm`

### ISSUE THREAD

**Issue by alhassy** [agda/agda-categories#23] opened 2019-07-18 19:14 UTC
The library should aim to be usable to those who do not make use of bleeding-edge Agda releases.

**Comment by JacquesCarette** [comment] 2019-07-18 20:02
See closed issue #10 for a discussion relating to this very topic.

**Comment by HuStmpHrrr** [comment] 2019-07-18 20:43
oops. sorry

**Comment by HuStmpHrrr** [comment] 2019-07-18 20:45
that being said, I think it is important to get the library clean in the first place. `levelOfTerm` is handy to keep universe level high-level. cleanup afterwards tends to be less optimal.

**Comment by gallais** [comment] 2019-07-18 20:53
Note that the issue title is misleading: the problem is not the compiler version
but the standard library one.

**Comment by HuStmpHrrr** [comment] 2019-09-07 20:10
fixed in https://github.com/agda/agda-categories/tree/release/v0.1

**Comment by asr** [comment] 2019-12-19 15:19
I'm getting the following error using Agda 2.6.0.1, standard library 1.1 and the [current](2d0a0cc0975e94a864ece5811308953f84e7f981) master:

```bash
agda Everything.agda
/some-path/Categories/Category/Monoidal/Braided.agda:25,23-34
Not in scope:
  levelOfTerm
  at /some-path/Categories/Category/Monoidal/Braided.agda:25,23-34

**Comment by HuStmpHrrr** [comment] 2019-12-19 15:46
> 
> 
> I'm getting the following error using Agda 2.6.0.1, standard library 1.1 and the [current](2d0a0cc0975e94a864ece5811308953f84e7f981) master:
> 
> ```shell
> $ agda Everything.agda
> /some-path/Categories/Category/Monoidal/Braided.agda:25,23-34
> Not in scope:
>   levelOfTerm
>   at /some-path/Categories/Category/Monoidal/Braided.agda:25,23-34
> ```

stdlib has released 1.2. I think the master branch of this library works with that version.

**Comment by JacquesCarette** [comment] 2019-12-19 16:08
I wonder if there is a way to put some code in `Everything.agda` to detect stdlib-1.2 (or lack thereof) early, so that we can fail gracefully?

**Comment by HuStmpHrrr** [comment] 2019-12-19 16:19
one possible (and dumb) way is to maintain a `Version-1.2.agda` file in stdlib for example, so that this file should be loaded before anything.

**Comment by asr** [comment] 2019-12-19 16:26
Oops! I had not updated my `.agda/libraries-2.6.0.1/` file. Thanks!

**Closed by asr** 2019-12-19 16:26 UTC
